### ISSUE TITLE
when to release the code 

### ISSUE THREAD

**Issue by Maguire1999** [rahul-goel/isrf#1]
Look forward to your excellent work.

**Comment by rahul-goel** [comment]
Hi Maguire.

Thanks for taking interest.
We'll definitely be releasing the code before end of March 2023.

Regards

**Comment by rahul-goel** [comment]
Hi @Maguire1999, the code is released at https://github.com/rahul-goel/isrf_code.

**Comment by Maguire1999** [comment]
Thanks



---Original---
From: "Rahul ***@***.***&gt;
Date: Wed, Mar 29, 2023 20:51 PM
To: ***@***.***&gt;;
Cc: "Yongjia ***@***.******@***.***&gt;;
Subject: Re: [rahul-goel/isrf] when to release the code  (Issue #1)




 
Closed #1 as completed.
